"""match/pair.py — REQ-006: the EXACTLY three MVP pair layers.

Level 4 (plan §4.1, docs/plans/2026-07-02-bazi-hehun.md). Imports Levels
0-4 only (sibling ``match`` modules, ``wuxing``); NEVER ``routers/*``,
``app``, ``limiter`` or ``services/*``. Pure functions — no I/O, no HTTP
shaping.

Binding contract anchors (docs/testing/bazi-hehun.acceptance-tests.md):
- AC-006a: the pair section carries EXACTLY ``day_master_comparison``,
  ``spouse_palace_day_branch`` and ``wuxing_vector_comparison`` — the
  frozen :class:`PairAnalysis` field set IS that layer set, so a fourth
  layer is unrepresentable without changing the type (D3).
- AC-006b: no interaction-matrix layer (branch/stem matrix, Ten Gods,
  Shen Sha) exists here — the deferred matrices (MISSING-001..003) are
  ABSENT from the contract, never stubbed.
- AC-006c: the token ``MISSING_INTERACTION_TABLE`` appears nowhere.
- AC-006d: layers contain calculated facts, rule applications and
  source-status markers only — NO numeric points, no score of any kind
  (D1/REQ-007). Numeric values occur only under the pinned computed-fact
  keys (the Wu-Xing vectors).

The day-master Wu-Xing relation is a RULE APPLICATION of the canonical
Sheng/Ke cycles, reused — not copied — from the repo's Level-4 sources:
the Sheng (generative, 相生) cycle is the element ORDER of
``wuxing.constants.WUXING_ORDER`` (each element generates its successor;
see the constant's docstring), and the Ke (controlling, 相剋) cycle is
the canonical ``wuxing.ke_cycle.KE_CYCLE`` table. Both agree with
``dayun.relation`` (``_produces = (e+1) % 5``, ``_controls = (e+2) % 5``)
by construction.
"""
from __future__ import annotations

import dataclasses
from dataclasses import dataclass
from typing import Dict, Final, Tuple

from ..wuxing.constants import WUXING_INDEX, WUXING_ORDER
from ..wuxing.ke_cycle import KE_CYCLE
from .individual import IndividualAnalysis
from .types import PAIR_LAYER_NAMES, Fact, PairLayer, SourceStatus

# The closed rule-application vocabulary of the day-master Wu-Xing
# relation (AC-006d): five values, partitioning the 5x5 element matrix
# exhaustively. ``a``/``b`` are POSITIONAL (first/second argument of
# :func:`analyze_pair`), matching the ``person_a_*``/``person_b_*`` fact
# key prefixes.
DAY_MASTER_RELATIONS: Final[Tuple[str, ...]] = (
    "same_element",
    "a_generates_b",
    "b_generates_a",
    "a_controls_b",
    "b_controls_a",
)

# Deterministic evidence-id namespace for pair layers. The T6 evidence
# ledger materializes exactly one entry per id emitted here (AC-013a).
_EVIDENCE_ID_TEMPLATE: Final[str] = "ev:pair:{layer}"


def pair_layer_evidence_id(layer_name: str) -> str:
    """Return the stable evidence-ledger id for a pair layer (AC-013a)."""
    return _EVIDENCE_ID_TEMPLATE.format(layer=layer_name)


def _generated_element(element: str) -> str:
    """Element generated by ``element`` per the canonical Sheng cycle.

    ``WUXING_ORDER`` is ordered along the generative cycle (相生), so the
    successor element IS the generated one — a lookup on the shared
    constant, not a re-derived table.

    Raises:
        KeyError: If ``element`` is not a ``WUXING_ORDER`` label.
    """
    return WUXING_ORDER[(WUXING_INDEX[element] + 1) % len(WUXING_ORDER)]


def classify_day_master_relation(element_a: str, element_b: str) -> str:
    """Classify the Wu-Xing relation between two day-master elements.

    Rule application of the canonical Sheng/Ke cycles (AC-006d) — the
    five arms of :data:`DAY_MASTER_RELATIONS` partition every element
    pair exhaustively (same discipline as
    ``dayun.relation._classify_element_relation``).

    Args:
        element_a: Person A's day-master element (``WUXING_ORDER`` label).
        element_b: Person B's day-master element (``WUXING_ORDER`` label).

    Returns:
        One of :data:`DAY_MASTER_RELATIONS`.

    Raises:
        KeyError: If either element is not a ``WUXING_ORDER`` label.
    """
    if element_a == element_b:
        return "same_element"
    if _generated_element(element_a) == element_b:
        return "a_generates_b"
    if KE_CYCLE[element_a] == element_b:
        return "a_controls_b"
    if _generated_element(element_b) == element_a:
        return "b_generates_a"
    if KE_CYCLE[element_b] == element_a:
        return "b_controls_a"
    # Unreachable: the five arms partition the 5x5 element matrix.
    raise AssertionError(
        f"unclassified element pair: {element_a!r} vs {element_b!r}"
    )


@dataclass(frozen=True)
class PairAnalysis:
    """The pair section — EXACTLY the three MVP layers (D3 / AC-006a).

    The field set IS the layer set (order pinned to
    ``PAIR_LAYER_NAMES``): a fourth layer cannot be emitted without
    changing this frozen type, which the AC-006 tests would catch.
    """

    day_master_comparison: PairLayer
    spouse_palace_day_branch: PairLayer
    wuxing_vector_comparison: PairLayer

    def layers(self) -> Dict[str, PairLayer]:
        """Return the layers keyed by their contract layer names."""
        return {
            f.name: getattr(self, f.name) for f in dataclasses.fields(self)
        }


def _day_master_comparison(
    person_a: IndividualAnalysis, person_b: IndividualAnalysis
) -> PairLayer:
    """Layer 1 — day-master facts (verbatim) + the Sheng/Ke rule application."""
    facts = (
        Fact(key="person_a_day_master", value=person_a.day_master),
        Fact(key="person_b_day_master", value=person_b.day_master),
        Fact(key="person_a_element", value=person_a.day_master_element),
        Fact(key="person_b_element", value=person_b.day_master_element),
        Fact(
            key="same_stem",
            value=person_a.day_master == person_b.day_master,
        ),
        Fact(
            key="same_element",
            value=person_a.day_master_element == person_b.day_master_element,
        ),
        Fact(
            key="day_master_wuxing_relation",
            value=classify_day_master_relation(
                person_a.day_master_element, person_b.day_master_element
            ),
        ),
    )
    return PairLayer(
        name="day_master_comparison",
        facts=facts,
        source_status=SourceStatus.CALCULATED,
        evidence_ids=(pair_layer_evidence_id("day_master_comparison"),),
    )


def _spouse_palace_day_branch(
    person_a: IndividualAnalysis, person_b: IndividualAnalysis
) -> PairLayer:
    """Layer 2 — spouse-palace/day-branch identification facts ONLY.

    The branch identities and ruleset hidden stems are deterministic
    (``CALCULATED``); the day-branch⇒spouse-palace DESIGNATION has no
    ruleset table (planning note a / audit F7), so the ``palace_pillar``
    fact and the layer itself are ``NEEDS_DOMAIN_REVIEW`` — never
    verified-looking, never interpretive.
    """
    palace_a = person_a.spouse_palace
    palace_b = person_b.spouse_palace
    facts = (
        Fact(
            key="palace_pillar",
            value=palace_a.palace_pillar,
            source_status=SourceStatus.NEEDS_DOMAIN_REVIEW,
        ),
        Fact(key="person_a_day_branch", value=palace_a.day_branch),
        Fact(key="person_b_day_branch", value=palace_b.day_branch),
        Fact(key="person_a_hidden_stems", value=palace_a.hidden_stems),
        Fact(key="person_b_hidden_stems", value=palace_b.hidden_stems),
        Fact(
            key="same_day_branch",
            value=palace_a.day_branch == palace_b.day_branch,
        ),
    )
    return PairLayer(
        name="spouse_palace_day_branch",
        facts=facts,
        source_status=SourceStatus.NEEDS_DOMAIN_REVIEW,
        evidence_ids=(pair_layer_evidence_id("spouse_palace_day_branch"),),
    )


def _wuxing_vector_comparison(
    person_a: IndividualAnalysis, person_b: IndividualAnalysis
) -> PairLayer:
    """Layer 3 — both Wu-Xing vectors verbatim, in canonical element order.

    The vectors come from the T2 normalization ledger, whose hidden-stem
    weighting binds to the legacy ``/calculate/wuxing`` source per user
    DECISION-003 — they are carried through untouched, never recomputed
    and never aggregated into any comparative number (D1).
    """
    facts = (
        Fact(key="element_order", value=tuple(WUXING_ORDER)),
        Fact(key="person_a_vector", value=person_a.wuxing_vector),
        Fact(key="person_b_vector", value=person_b.wuxing_vector),
    )
    return PairLayer(
        name="wuxing_vector_comparison",
        facts=facts,
        source_status=SourceStatus.CALCULATED,
        evidence_ids=(pair_layer_evidence_id("wuxing_vector_comparison"),),
    )


def analyze_pair(
    person_a: IndividualAnalysis, person_b: IndividualAnalysis
) -> PairAnalysis:
    """Compute the pair analysis — EXACTLY the three MVP layers (REQ-006).

    Args:
        person_a: First person's :class:`IndividualAnalysis` (T3 output);
                  its values populate the ``person_a_*`` facts verbatim.
        person_b: Second person's analysis, populating ``person_b_*``.

    Returns:
        A frozen :class:`PairAnalysis` whose layers carry calculated
        facts, rule applications and source-status markers only — no
        numeric points, no matrix content, no stubs (AC-006a-d).
    """
    analysis = PairAnalysis(
        day_master_comparison=_day_master_comparison(person_a, person_b),
        spouse_palace_day_branch=_spouse_palace_day_branch(person_a, person_b),
        wuxing_vector_comparison=_wuxing_vector_comparison(person_a, person_b),
    )
    assert tuple(analysis.layers()) == PAIR_LAYER_NAMES
    return analysis
